/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ApiKeyUpdateManyWithoutAppsInput } from "./ApiKeyUpdateManyWithoutAppsInput";
import { ValidateNested, IsOptional, IsEnum, IsString } from "class-validator";
import { Type } from "class-transformer";
import { EnumAppCategories } from "./EnumAppCategories";
import { CredentialUpdateManyWithoutAppsInput } from "./CredentialUpdateManyWithoutAppsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { WebhookUpdateManyWithoutAppsInput } from "./WebhookUpdateManyWithoutAppsInput";

@InputType()
class AppUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ApiKeyUpdateManyWithoutAppsInput,
  })
  @ValidateNested()
  @Type(() => ApiKeyUpdateManyWithoutAppsInput)
  @IsOptional()
  @Field(() => ApiKeyUpdateManyWithoutAppsInput, {
    nullable: true,
  })
  apiKey?: ApiKeyUpdateManyWithoutAppsInput;

  @ApiProperty({
    required: false,
    enum: EnumAppCategories,
    isArray: true,
  })
  @IsEnum(EnumAppCategories, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumAppCategories], {
    nullable: true,
  })
  categories?: Array<
    "calendar" | "messaging" | "other" | "payment" | "video" | "web3"
  >;

  @ApiProperty({
    required: false,
    type: () => CredentialUpdateManyWithoutAppsInput,
  })
  @ValidateNested()
  @Type(() => CredentialUpdateManyWithoutAppsInput)
  @IsOptional()
  @Field(() => CredentialUpdateManyWithoutAppsInput, {
    nullable: true,
  })
  credentials?: CredentialUpdateManyWithoutAppsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  dirName?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  keys?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => WebhookUpdateManyWithoutAppsInput,
  })
  @ValidateNested()
  @Type(() => WebhookUpdateManyWithoutAppsInput)
  @IsOptional()
  @Field(() => WebhookUpdateManyWithoutAppsInput, {
    nullable: true,
  })
  webhook?: WebhookUpdateManyWithoutAppsInput;
}

export { AppUpdateInput as AppUpdateInput };
